services:
  backend:
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./backend/.env
    networks:
      - flip-network
    ports:
      - "8080:8080"

  database:
    image: postgres:17.3-alpine
    environment:
      POSTGRES_USER: flip
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - flip-network
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - flip-db:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - flip-network
    ports:
      - "3000:3000"

networks:
  flip-network:

volumes:
  flip-db:
