REVOKE CONNECT ON DATABASE flip FROM PUBLIC;
GRANT CONNECT ON DATABASE flip TO flip;

-- Non-root app user for db operations
CREATE USER app WITH CONNECTION LIMIT 3 PASSWORD 'password';

GRANT CONNECT ON DATABASE flip TO app;
GRANT USAGE ON SCHEMA public TO app;
GRANT TEMP ON DATABASE flip TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app;

ALTER DEFAULT PRIVILEGES FOR ROLE flip IN SCHEMA public GRANT SELECT, INSERT, DELETE, UPDATE ON TABLES TO app;
ALTER DEFAULT PRIVILEGES FOR ROLE flip IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO app;

-- Schema
CREATE TABLE Product
(
    SKU       VARCHAR(10) PRIMARY KEY,
    Name      VARCHAR(255)   NOT NULL,
    Price     DECIMAL(10, 2) NOT NULL,
    Inventory INT            NOT NULL
);

INSERT INTO Product (SKU, Name, Price, Inventory)
VALUES ('120P90', 'Google TV', 49.99, 10),
       ('43N23P', 'MacBook Pro', 5399.99, 5),
       ('A304SD', 'Alexa Speaker', 109.50, 10),
       ('234234', 'Raspberry Pi B', 30.00, 2);