REVOKE CONNECT ON DATABASE flip FROM PUBLIC;
GRANT CONNECT ON DATABASE flip TO flip;

-- Non-root app user for db operations
CREATE USER app WITH CONNECTION LIMIT 3 PASSWORD 'password';

GRANT CONNECT ON DATABASE flip TO app;
GRANT USAGE ON SCHEMA public TO app;
GRANT TEMP ON DATABASE flip TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app;

ALTER DEFAULT PRIVILEGES FOR ROLE flip IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO app;
ALTER DEFAULT PRIVILEGES FOR ROLE flip IN SCHEMA public GRANT SELECT,USAGE ON SEQUENCES TO app;